import Head from "next/head";
import util from "../../styles/util.module.css";

export default function Home() {
  return (
    <div className={util.container}>
      <Head>
        <title>Writings | shak&apos;s corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={util.main}>
        <div className={util.title}>{/* <h1>Writings</h1> */}</div>

        <div className={util.content}>
          <p>🚧 Page Under Construction 🚧</p>
        </div>
      </main>
    </div>
  );
}
