import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Work | shak&apos;s corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.homeHeader}>
          <div className={styles.title}>
            <h1>Work</h1>
          </div>
        </div>

        <div className={styles.description}>
          <p>
            I am a Software Engineer working as a Front end Developer for
            <a href="http://liqid.de/"> Liqid Investments</a>, Berlin. I
            previously worked for <a href="https://www.zoho.com/">Zoho</a> where
            I was an integral part of the development of a design collaboration
            application called <a href="https://nila.cloud/">Nila.</a> I prefer
            front end. I can do back end.
          </p>
        </div>
      </main>
    </div>
  );
}
