import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home | shak&apos;s corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.homeHeader}>
          <div className={styles.title}>
            <h1>shak&apos;s </h1>
            <h1>corner</h1>
          </div>
          <div>
            {/* <Image
              priority
              // className={iconClassName}
              src={`/icons/Corner.svg`}
              height={120}
              width={120}
              alt="Theme-changer"
              // onClick={clickHander}
            /> */}
            <div className={styles.subtitle}>
              <p>Making things.</p>
              <p>Writing code.</p>
              <p>Minimalist.</p>
            </div>
          </div>
        </div>

        <div className={styles.description}>
          <p>
            I am a Software Engineer working as a Front end Developer for
            <a href="http://liqid.de/"> Liqid Investments</a>, Berlin. I
            previously worked for <a href="https://www.zoho.com/">Zoho</a> where
            I was an integral part of the development of a design collaboration
            application called <a href="https://nila.cloud/">Nila.</a> I prefer
            front end. I can do back end.
          </p>

          <p>
            I consider myself a Minimalist, and a digital privacy advocate.
            Always curious and to some extend perplexed by the rapid evolution
            of trends in technology.
          </p>

          <p>
            I consider myself a Minimalist, and a digital privacy advocate.
            Always curious and to some extend perplexed by the rapid evolution
            of trends in technology.
          </p>

          <p>
            I consider myself a Minimalist, and a digital privacy advocate.
            Always curious and to some extend perplexed by the rapid evolution
            of trends in technology.
          </p>

          <p>
            I have always been fascinated by tools of thought and am currently
            in the neverending pursuit of finding that one <b>perfect</b> tool
            to add it to my stack.
          </p>

          <p>
            Here&apos;s what I&apos;m doing right <a href="/now/">now</a>.
          </p>
        </div>
      </main>
    </div>
  );
}
